const KEY="stocks-web-v6";
const LEGACY_KEYS=["stocks-web-v5","stocks-web-v4","stocks-web-v3","stocks-web-v2"];
const DEFAULT_SYMBOL="عیار";
const initialData=[
  ["1405/04/28",10,520000,6240],["1405/04/29",10,510000,6120],
  ["1405/05/04",10,500000,6000],["1405/05/31",10,580000,6960],
  ["1405/05/31",10,583000,6996],["1405/05/31",10,583000,6996],
  ["1405/05/31",10,590000,7080],["1405/06/02",10,610000,7320],
  ["1405/06/03",10,600000,7200],["1405/06/15",110,640000,84480],
  ["1405/06/16",100,630000,75600],["1405/06/22",100,640000,38496],
  ["1405/06/24",16,630000,0],["1405/07/01",384,650000,0],
  ["1405/07/08",150,710000,85200]
];
const $=s=>document.querySelector(s), rowsEl=$("#rows");
let app=loadApp(), activeSymbol=app.activeSymbol||DEFAULT_SYMBOL, currentView=app.currentView||"dashboard", calendarTarget=null, calendarCursor=null, draggedSymbol=null, chartHitboxes=[];

function faToEn(s){return String(s??"").replace(/[۰-۹]/g,c=>"۰۱۲۳۴۵۶۷۸۹".indexOf(c)).replace(/[٠-٩]/g,c=>"٠١٢٣٤٥٦٧٨٩".indexOf(c)).replace(/٫/g,".").replace(/٬/g,"").replace(/,/g,"").replace(/[\/\\-]/g,"/")}
function enToFa(s){return String(s??"").replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[d])}
function num(v){return Number(faToEn(v).replace(/[^0-9.+-]/g,""))||0}
function fmt(v){return Math.round(v||0).toLocaleString("fa-IR")}
function fmtPct(v){return (v*100).toLocaleString("fa-IR",{minimumFractionDigits:2,maximumFractionDigits:2})+"٪"}
function formatNumericInput(input,decimal=false){let s=faToEn(input.value).replace(/[^0-9.]/g,"");if(decimal){const p=s.split(".");s=p[0]+(p.length>1?"."+p.slice(1).join(""):"")}else s=s.split(".")[0];input.value=enToFa(s.replace(".","٫"))}
function div(a,b){return Math.floor(a/b)}
function jalaliToGregorian(jy,jm,jd){jy=+jy;jm=+jm;jd=+jd;const epBase=jy-(jy>=0?474:473),epYear=474+((epBase%2820+2820)%2820),md=jm<=7?(jm-1)*31:(jm-1)*30+6,days=jd+md+div(epYear*682-110,2816)+(epYear-1)*365+div(epBase,2820)*1029983+(1948320-1);let gy=400*div(days,146097),rem=days%146097;if(rem>=36524){gy+=100*div(--rem,36524);rem%=36524;if(rem>=365)rem++}let yday=rem;gy+=4*div(yday,1461);yday%=1461;if(yday>=366){gy+=div(yday-1,365);yday=(yday-1)%365}let gd=yday+1;const leap=(gy%4===0&&gy%100!==0)||gy%400===0,sal=leap?[31,29,31,30,31,30,31,31,30,31,30,31]:[31,28,31,30,31,30,31,31,30,31,30,31];let gm=1;while(gd>sal[gm-1]){gd-=sal[gm-1];gm++}return {gy,gm,gd,date:new Date(Date.UTC(gy,gm-1,gd))}}
function parseJ(s){const a=faToEn(s).split("/").map(Number);if(a.length!==3||!a.every(Number.isFinite))return null;const [y,m,d]=a;if(y<1200||y>1600||m<1||m>12||d<1||d>(m<=6?31:m<=11?30:30))return null;return {y,m,d,...jalaliToGregorian(y,m,d)}}
function currentJalali(){const p=new Intl.DateTimeFormat("fa-IR-u-ca-persian-nu-latn",{year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),g=t=>Number(p.find(x=>x.type===t)?.value);return {y:g("year"),m:g("month"),d:g("day")}}
function daysBetweenJalali(date){const d=parseJ(date);if(!d)return null;const n=currentJalali(),now=jalaliToGregorian(n.y,n.m,n.d);return Math.max(0,Math.round((now.date-d.date)/86400000))}
function dateAddDays(jdate,days){const d=parseJ(jdate);if(!d)return null;const g=new Date(d.date.getTime()+days*86400000);return gregorianToJalali(g)}
function gregorianToJalali(date){const gy=date.getUTCFullYear(),gm=date.getUTCMonth()+1,gd=date.getUTCDate();const jy=gy-621;let start=jalaliToGregorian(jy,1,1);let y=jy;if(date<start){y--;start=jalaliToGregorian(y,1,1)}const k=Math.round((date-start.date)/86400000);let m,d;if(k<=185){m=1+Math.floor(k/31);d=k%31+1}else{const q=k-186;m=7+Math.floor(q/30);d=q%30+1}return `${enToFa(y)}/${enToFa(String(m).padStart(2,"0"))}/${enToFa(String(d).padStart(2,"0"))}`}
function makeId(){return crypto.randomUUID?.()||String(Date.now()+Math.random())}
function makeSymbol(rows=initialData,price=713145,sellFee=.12){return {price, sellFee, rows:rows.map(x=>({id:makeId(),date:x[0],shares:x[1],price:x[2],commission:x[3]}))}}
function normalizeApp(a){
  if(a?.symbols&&typeof a.symbols==="object"){
    const symbols={};const legacyFee=a.sellFee!=null?+a.sellFee:.12;Object.entries(a.symbols).forEach(([name,s])=>{symbols[name]={price:+s.price||0,sellFee:s.sellFee!=null?+s.sellFee:legacyFee,rows:Array.isArray(s.rows)?s.rows.map(r=>({id:r.id||makeId(),date:r.date||"",shares:+r.shares||0,price:+r.price||0,commission:+r.commission||0})):[]}});
    let order=Array.isArray(a.symbolOrder)?a.symbolOrder.filter(n=>symbols[n]):Object.keys(symbols);Object.keys(symbols).forEach(n=>{if(!order.includes(n))order.push(n)});
    if(!Object.keys(symbols).length){symbols[DEFAULT_SYMBOL]=makeSymbol();order=[DEFAULT_SYMBOL]}
    return {version:6,activeSymbol:a.activeSymbol&&symbols[a.activeSymbol]?a.activeSymbol:order[0],symbolOrder:order,symbols,chartSymbol:a.chartSymbol||"all",currentView:a.currentView||"dashboard"};
  }
  const symbols={[DEFAULT_SYMBOL]:makeSymbol()};
  if(a?.price!=null)symbols[DEFAULT_SYMBOL].price=+a.price||713145;
  if(a?.fee!=null)symbols[DEFAULT_SYMBOL].sellFee=+a.fee||.12;
  if(Array.isArray(a?.rows)&&a.rows.length)symbols[DEFAULT_SYMBOL].rows=a.rows.map(r=>({id:makeId(),date:r.date||"",shares:+r.shares||0,price:+r.price||0,commission:+r.commission||0}));
  return {version:6,activeSymbol:DEFAULT_SYMBOL,symbolOrder:[DEFAULT_SYMBOL],symbols,chartSymbol:"all",currentView:"dashboard"};
}
function loadApp(){
  for(const key of [KEY,...LEGACY_KEYS]){try{const v=JSON.parse(localStorage.getItem(key)||"null");if(v){const n=normalizeApp(v);if(Object.keys(n.symbols).some(k=>n.symbols[k].rows.length>0)||key===KEY)return n}}catch(e){}}
  return {version:6,activeSymbol:DEFAULT_SYMBOL,symbolOrder:[DEFAULT_SYMBOL],chartSymbol:"all",symbols:{[DEFAULT_SYMBOL]:makeSymbol()}};
}
function saveApp(){app.version=6;app.activeSymbol=activeSymbol;app.currentView=currentView;localStorage.setItem(KEY,JSON.stringify(app))}
function active(){return app.symbols[activeSymbol]}
function sortRows(){active().rows.sort((a,b)=>(parseJ(b.date)?.date-parseJ(a.date)?.date)||0)}
function renderSymbols(){const el=$("#symbolList");el.innerHTML="";for(const name of app.symbolOrder){const s=app.symbols[name];if(!s)continue;const b=document.createElement("button");b.className="symbol-btn"+(name===activeSymbol?" active":"");b.draggable=true;b.dataset.symbol=name;b.innerHTML=`<span class="drag-handle">⠿</span><span class="symbol-name">${escapeHtml(name)}</span><span class="symbol-count">${enToFa(String(s.rows.length))}</span>`;b.onclick=()=>switchSymbol(name);b.ondblclick=e=>{e.stopPropagation();renameSymbol(name)};b.ondragstart=()=>{draggedSymbol=name;b.classList.add("dragging")};b.ondragend=()=>{draggedSymbol=null;b.classList.remove("dragging")};b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();if(draggedSymbol&&draggedSymbol!==name){const from=app.symbolOrder.indexOf(draggedSymbol),to=app.symbolOrder.indexOf(name);app.symbolOrder.splice(from,1);app.symbolOrder.splice(to,0,draggedSymbol);renderSymbols();saveApp()}};el.appendChild(b)}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function switchSymbol(name){activeSymbol=name;currentView="symbol";sortRows();renderSymbols();render();saveApp()}
function renameSymbol(oldName){const n=prompt("نام جدید نماد را وارد کنید:",oldName)?.trim();if(!n||n===oldName)return;if(app.symbols[n])return alert("این نام قبلاً استفاده شده است.");app.symbols[n]=app.symbols[oldName];delete app.symbols[oldName];const i=app.symbolOrder.indexOf(oldName);app.symbolOrder[i]=n;if(activeSymbol===oldName)activeSymbol=n;if(app.chartSymbol===oldName)app.chartSymbol=n;renderSymbols();render();saveApp()}
function addRow(data={date:"",shares:"",price:"",commission:""}){const tr=$("#rowTemplate").content.firstElementChild.cloneNode(true);tr.dataset.id=data.id||makeId();tr.querySelector(".jalali").value=data.date?enToFa(data.date):"";tr.querySelector(".shares").value=data.shares?enToFa(data.shares):"";tr.querySelector(".price").value=data.price?enToFa(data.price):"";tr.querySelector(".commission").value=data.commission?enToFa(data.commission):"";rowsEl.appendChild(tr);tr.querySelector(".date-input").onclick=()=>openCalendar(tr);[".shares",".price",".commission"].forEach(sel=>tr.querySelector(sel).oninput=()=>{formatNumericInput(tr.querySelector(sel));syncRows();updateCalculations();saveApp()});tr.querySelector(".delete").onclick=()=>{if(confirm(`خرید مورخ «${tr.querySelector(".jalali").value||"بدون تاریخ"}» حذف شود؟`)){tr.remove();syncRows();render();saveApp()}}}
function syncRows(){active().rows=[...rowsEl.querySelectorAll("tr")].map(tr=>({id:tr.dataset.id,date:faToEn(tr.querySelector(".jalali").value),shares:num(tr.querySelector(".shares").value),price:num(tr.querySelector(".price").value),commission:num(tr.querySelector(".commission").value)}));sortRows()}
function rowMetrics(r,s=active()){
  const cost=r.shares*r.price+r.commission, fee=(s.sellFee??.12)/100, price=s.price;
  const net=price*r.shares*(1-fee), profit=cost&&price?(net-cost)/cost:null;
  const elapsed=daysBetweenJalali(r.date), targetValue=cost*2, targetPrice=r.shares&&fee<1?targetValue/(r.shares*(1-fee)):r.price*2, progress=targetValue?net/targetValue:null;
  const remaining=elapsed==null?null:Math.max(0,365-elapsed), targetDate=dateAddDays(r.date,365);
  return {cost,net,profit,elapsed,targetPrice,targetValue,progress,remaining,targetDate};
}
function updateCalculations(){const s=active();rowsEl.querySelectorAll("tr").forEach(tr=>{const r={date:faToEn(tr.querySelector(".jalali").value),shares:num(tr.querySelector(".shares").value),price:num(tr.querySelector(".price").value),commission:num(tr.querySelector(".commission").value)},m=rowMetrics(r,s);tr.querySelector(".cost").textContent=m.cost?fmt(m.cost):"—";tr.querySelector(".live-price").textContent=s.price?fmt(s.price):"—";tr.querySelector(".days").textContent=m.elapsed==null?"—":enToFa(m.elapsed);tr.querySelector(".profit").textContent=m.profit==null?"—":fmtPct(m.profit);tr.querySelector(".profit").classList.toggle("positive",m.profit>0);tr.querySelector(".profit").classList.toggle("negative",m.profit<0);tr.querySelector(".target").innerHTML=m.targetPrice?`<strong>${fmt(m.targetPrice)}</strong><small>${m.targetDate?`تا ${m.targetDate}`:""}</small>`:"—"});drawChart()}
function symbolMetrics(name){const s=app.symbols[name],fee=(s.sellFee??.12)/100;let shares=0,cost=0,value=0;for(const r of s.rows){const m=rowMetrics(r,s);shares+=r.shares;cost+=m.cost;value+=r.shares*s.price}const net=value*(1-fee),pnl=cost&&s.price?net-cost:null,ret=pnl==null?null:pnl/cost;return {shares,cost,value,net,pnl,ret}}
function renderDashboard(){let totalCost=0,totalValue=0,totalNet=0;const body=$("#dashboardRows");body.innerHTML="";for(const name of app.symbolOrder){const s=app.symbols[name],m=symbolMetrics(name);totalCost+=m.cost;totalValue+=m.value;totalNet+=m.net;const target=m.cost*2,progress=target?m.net/target:null,tr=document.createElement("tr");tr.innerHTML=`<td><button class="table-symbol" data-symbol="${escapeHtml(name)}">${escapeHtml(name)}</button></td><td>${fmt(m.shares)}</td><td>${m.cost?fmt(m.cost):"—"}</td><td><input class="dash-price" data-symbol="${escapeHtml(name)}" value="${s.price?fmt(s.price):""}" inputmode="numeric"></td><td><div class="dash-fee suffix-input"><input class="dash-sellfee" data-symbol="${escapeHtml(name)}" value="${enToFa(Number(s.sellFee??.12).toFixed(2)).replace(".","٫")}" inputmode="decimal"><small>٪</small></div></td><td>${m.value?fmt(m.value):"—"}</td><td class="${m.pnl>0?"positive":m.pnl<0?"negative":""}">${m.pnl==null?"—":fmt(m.pnl)}</td><td class="${m.ret>0?"positive":m.ret<0?"negative":""}">${m.ret==null?"—":fmtPct(m.ret)}</td><td>${progress==null?"—":`<div class="dash-progress"><div><i style="width:${Math.min(100,Math.max(0,progress*100))}%"></i></div><span>${enToFa((progress*100).toFixed(1))}٪</span></div>`}</td>`;body.appendChild(tr)}const netPnl=totalNet-totalCost,ret=totalCost?netPnl/totalCost:null;$("#dashValue").textContent=totalValue?fmt(totalValue):"—";$("#dashPnl").textContent=totalCost?fmt(netPnl):"—";$("#dashProfit").textContent=ret==null?"—":fmtPct(ret);$("#dashSymbols").textContent=enToFa(app.symbolOrder.length);$("#dashPnl").className=netPnl>0?"positive":netPnl<0?"negative":"";$("#dashProfit").className=ret>0?"positive":ret<0?"negative":"";body.querySelectorAll(".table-symbol").forEach(b=>b.onclick=()=>switchSymbol(b.dataset.symbol));body.querySelectorAll(".dash-price").forEach(i=>{i.oninput=()=>{formatNumericInput(i);app.symbols[i.dataset.symbol].price=num(i.value);saveApp()};i.onchange=()=>{renderDashboard();drawChart();saveApp()}});body.querySelectorAll(".dash-sellfee").forEach(i=>{i.oninput=()=>{formatNumericInput(i,true);app.symbols[i.dataset.symbol].sellFee=num(i.value)||.12;saveApp()};i.onchange=()=>{renderDashboard();drawChart();saveApp()}})}
function showView(){$("#dashboardView").hidden=currentView!=="dashboard";$("#symbolView").hidden=currentView!=="symbol";$("#dashboardBtn").classList.toggle("active",currentView==="dashboard")}
function render(){sortRows();rowsEl.innerHTML="";const s=active();if(!s.rows.length){rowsEl.innerHTML=`<tr><td colspan="10" class="empty-table">هنوز خریدی برای این نماد ثبت نشده است. برای شروع روی «＋ خرید جدید» کلیک کنید.</td></tr>`}else s.rows.forEach(r=>addRow(r));updateCalculations();renderDashboard();showView()}

function openCalendar(tr){calendarTarget=tr;const p=parseJ(tr.querySelector(".jalali").value);const now=currentJalali();calendarCursor=p?{y:p.y,m:p.m}:{y:now.y,m:now.m};renderCalendar();$("#dateModal").classList.add("open");$("#dateModal").setAttribute("aria-hidden","false")}
function closeCalendar(){$("#dateModal").classList.remove("open");$("#dateModal").setAttribute("aria-hidden","true");calendarTarget=null}
function monthDays(y,m){return m<=6?31:m<=11?30:Math.round((jalaliToGregorian(y+1,1,1).date-jalaliToGregorian(y,12,1).date)/86400000)}
function renderCalendar(){const {y,m}=calendarCursor;$("#calendarTitle").textContent=`${["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"][m-1]} ${enToFa(y)}`;const first=jalaliToGregorian(y,m,1).date.getUTCDay(),offset=(first+1)%7,days=monthDays(y,m),selected=parseJ(calendarTarget?.querySelector(".jalali")?.value||""),today=currentJalali(),g=$("#calendarGrid");g.innerHTML="";for(let i=0;i<offset;i++){const e=document.createElement("button");e.className="empty";g.appendChild(e)}for(let d=1;d<=days;d++){const b=document.createElement("button");b.textContent=enToFa(d);if(today.y===y&&today.m===m&&today.d===d)b.classList.add("today");if(selected?.y===y&&selected?.m===m&&selected?.d===d)b.classList.add("selected");b.onclick=()=>selectDate(y,m,d);g.appendChild(b)}}
function selectDate(y,m,d){if(!calendarTarget)return;calendarTarget.querySelector(".jalali").value=`${enToFa(String(y))}/${enToFa(String(m).padStart(2,"0"))}/${enToFa(String(d).padStart(2,"0"))}`;syncRows();closeCalendar();render();saveApp()}
$("#prevMonth").onclick=()=>{calendarCursor.m--;if(calendarCursor.m<1){calendarCursor.m=12;calendarCursor.y--}renderCalendar()};$("#nextMonth").onclick=()=>{calendarCursor.m++;if(calendarCursor.m>12){calendarCursor.m=1;calendarCursor.y++}renderCalendar()};$("#todayBtn").onclick=()=>{const t=currentJalali();calendarCursor={y:t.y,m:t.m};renderCalendar()};$("#closeCalendar").onclick=closeCalendar;$("#dateModal").onclick=e=>{if(e.target.id==="dateModal")closeCalendar()};
$("#dashboardBtn").onclick=()=>{currentView="dashboard";render();saveApp()};
$("#addBtn").onclick=()=>{active().rows.unshift({id:makeId(),date:"",shares:"",price:"",commission:""});render();saveApp()};
$("#addSymbolBtn").onclick=()=>{const name=prompt("نام نماد را وارد کنید:");if(!name)return;const n=name.trim();if(!n||app.symbols[n])return alert("این نماد قبلاً وجود دارد.");app.symbols[n]=makeSymbol([],0,.12);app.symbolOrder.push(n);activeSymbol=n;renderSymbols();render();saveApp()};
$("#resetBtn").onclick=()=>{if(confirm("تمام نمادها، خریدها، قیمت‌های پایانی، کارمزدها و تنظیمات ذخیره‌شده حذف شوند؟ این عملیات قابل بازگشت نیست.")){localStorage.removeItem(KEY);location.reload()}};

function chartData(){const selected=app.chartSymbol||"all",list=[];for(const name of app.symbolOrder){if(selected!=="all"&&selected!==name)continue;const s=app.symbols[name];for(const r of s.rows){const m=rowMetrics(r,s);if(m.profit!=null&&parseJ(r.date))list.push({symbol:name,date:r.date,profit:m.profit,shares:r.shares,price:r.price})}}return list.sort((a,b)=>(parseJ(a.date)?.date-parseJ(b.date)?.date)||a.symbol.localeCompare(b.symbol,"fa"))}
function drawChart(){const canvas=$("#profitChart"),empty=$("#chartEmpty"),wrap=$("#chartWrap"),points=chartData();chartHitboxes=[];if(!points.length){empty.style.display="grid";canvas.style.display="none";return}empty.style.display="none";canvas.style.display="block";const dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);const pad={l:52,r:20,t:22,b:52},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,vals=points.map(p=>p.profit*100),min=Math.min(0,...vals),max=Math.max(0,...vals),span=Math.max(1,max-min),barSpace=cw/points.length,barW=Math.max(8,Math.min(42,barSpace*.62)),y=v=>pad.t+(max-v)/span*ch,zero=y(0);ctx.font="11px Vazirmatn";ctx.strokeStyle="#dfe4e9";ctx.fillStyle="#70777f";ctx.textAlign="right";for(const v of [min,(min+max)/2,max]){ctx.beginPath();ctx.moveTo(pad.l,y(v));ctx.lineTo(w-pad.r,y(v));ctx.stroke();ctx.fillText(enToFa(v.toFixed(1))+"٪",pad.l-8,y(v)+4)}points.forEach((p,i)=>{const v=p.profit*100,x=pad.l+i*barSpace+(barSpace-barW)/2,top=y(Math.max(0,v)),bottom=y(Math.min(0,v));ctx.fillStyle=v>=0?"#138a4b":"#c62828";ctx.fillRect(x,top,barW,Math.max(2,bottom-top));chartHitboxes.push({x,top:Math.min(top,bottom),y:Math.max(top,bottom),w:barW,h:Math.abs(bottom-top),point:p})});ctx.strokeStyle="#8f969e";ctx.beginPath();ctx.moveTo(pad.l,zero);ctx.lineTo(w-pad.r,zero);ctx.stroke();ctx.textAlign="center";ctx.fillStyle="#70777f";const step=Math.max(1,Math.ceil(points.length/8));points.forEach((p,i)=>{if(i%step===0)ctx.fillText(enToFa(p.date.slice(5)),pad.l+i*barSpace+barSpace/2,h-15)})}
function chartTooltip(e){const canvas=$("#profitChart"),rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,t=$("#chartTooltip");const hit=chartHitboxes.find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(!hit){t.hidden=true;return}t.innerHTML=`<strong>${escapeHtml(hit.point.symbol)}</strong><br>تاریخ: ${enToFa(hit.point.date)}<br>سود/زیان: <b class="${hit.point.profit>=0?"positive":"negative"}">${fmtPct(hit.point.profit)}</b>`;t.hidden=false;t.style.left=Math.min(x+12,rect.width-180)+"px";t.style.top=Math.max(8,y-12)+"px"}
$("#profitChart").addEventListener("mousemove",chartTooltip);$("#profitChart").addEventListener("mouseleave",()=>$("#chartTooltip").hidden=true);$("#chartSymbolFilter").onchange=e=>{app.chartSymbol=e.target.value;saveApp();drawChart()};

function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvEscape(v){const s=String(v??"");return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportJson(){downloadBlob(new Blob([JSON.stringify(app,null,2)],{type:"application/json;charset=utf-8"}),"درصد-سود-بورس-پشتیبان.json")}
function exportCsv(){const lines=[["نماد","تاریخ","تعداد سهم","قیمت","کارمزد","مبلغ خرید","قیمت پایانی سهم","کارمزد فروش","مدت (روز)","درصد سود","هدف ۱۰۰٪"]];for(const name of app.symbolOrder){const s=app.symbols[name];s.rows.forEach(r=>{const m=rowMetrics(r,s);lines.push([name,r.date,r.shares,r.price,r.commission,m.cost,s.price,s.sellFee,m.elapsed??"",m.profit==null?"":(m.profit*100).toFixed(2),m.targetPrice])})}const csv="\uFEFF"+lines.map(r=>r.map(csvEscape).join(",")).join("\n");downloadBlob(new Blob([csv],{type:"text/csv;charset=utf-8"}),"درصد-سود-بورس-پشتیبان.csv")}
function openBackup(){openChoiceModal("پشتیبان",["JSON","CSV"],v=>v==="JSON"?exportJson():exportCsv())}
function openRestore(){openChoiceModal("بازیابی",["JSON","CSV"],v=>v==="JSON"?$("#importJsonFile").click():$("#importCsvFile").click())}
function openChoiceModal(title,choices,cb){const m=$("#choiceModal"),body=$("#choiceBody");$("#choiceTitle").textContent=title;body.innerHTML="";choices.forEach(c=>{const b=document.createElement("button");b.className="choice-btn";b.textContent=c;b.onclick=()=>{m.classList.remove("open");cb(c)};body.appendChild(b)});m.classList.add("open")}
$("#backupBtn").onclick=openBackup;$("#restoreBtn").onclick=openRestore;$("#closeChoice").onclick=()=>$("#choiceModal").classList.remove("open");$("#choiceModal").onclick=e=>{if(e.target.id==="choiceModal")e.currentTarget.classList.remove("open")};
function bindImport(inputId,kind){$(inputId).onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const text=await f.text();if(kind==="json"){const incoming=normalizeApp(JSON.parse(text));if(confirm("داده‌های فعلی با داده‌های فایل جایگزین شوند؟")){app=incoming;activeSymbol=app.activeSymbol||app.symbolOrder[0];localStorage.setItem(KEY,JSON.stringify(app));renderSymbols();render()}}else importCsv(text);e.target.value=""}catch(err){alert("فایل قابل خواندن نیست.")}}}
bindImport("#importJsonFile","json");bindImport("#importCsvFile","csv");
function importCsv(text){const rows=parseCsv(text.replace(/^\uFEFF/,""));if(rows.length<2)return alert("فایل CSV داده‌ای ندارد.");const h=rows[0],idx=n=>h.indexOf(n),required=["نماد","تاریخ","تعداد سهم","قیمت","کارمزد"];if(required.some(x=>idx(x)<0))return alert("ستون‌های لازم CSV پیدا نشد.");const grouped={};rows.slice(1).forEach(r=>{const name=r[idx("نماد")]?.trim()||DEFAULT_SYMBOL;(grouped[name]??=[]).push({id:makeId(),date:faToEn(r[idx("تاریخ")]||""),shares:num(r[idx("تعداد سهم")]),price:num(r[idx("قیمت")]),commission:num(r[idx("کارمزد")])})});Object.entries(grouped).forEach(([name,rs])=>{if(!app.symbols[name]){app.symbols[name]=makeSymbol([],0,.12);app.symbolOrder.push(name)}app.symbols[name].rows=rs});activeSymbol=Object.keys(grouped)[0]||activeSymbol;renderSymbols();render();saveApp()}
function parseCsv(text){const out=[];let row=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(quote){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quote=false;else cell+=c}else if(c==='"')quote=true;else if(c===','){row.push(cell);cell=""}else if(c==='\n'){row.push(cell);out.push(row);row=[];cell=""}else if(c!=='\r')cell+=c}row.push(cell);if(row.length>1||row[0])out.push(row);return out}

$("#editSymbolBtn").onclick=()=>renameSymbol(activeSymbol);$("#deleteSymbolBtn").onclick=()=>{if(Object.keys(app.symbols).length<=1)return alert("حداقل یک نماد باید باقی بماند.");if(confirm(`نماد «${activeSymbol}» و تمام ${enToFa(active().rows.length)} خرید آن حذف شود؟`)){const old=activeSymbol;delete app.symbols[old];app.symbolOrder=app.symbolOrder.filter(n=>n!==old);activeSymbol=app.symbolOrder[0];if(app.chartSymbol===old)app.chartSymbol="all";renderSymbols();render();saveApp()}};
function updateChartFilter(){const sel=$("#chartSymbolFilter"),current=app.chartSymbol||"all";sel.innerHTML=`<option value="all">همهٔ نمادها</option>`+app.symbolOrder.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join("");sel.value=app.symbols[current]?current:"all";app.chartSymbol=sel.value}
function updateEmptyStates(){const hasAny=app.symbolOrder.some(n=>app.symbols[n]?.rows?.length);$("#chartPanel").classList.toggle("empty-panel",!hasAny)}
window.addEventListener("resize",drawChart);
function finalRender(){renderSymbols();updateChartFilter();render();updateEmptyStates()}
finalRender();
